/**
 * Mock Model Registry Data
 * For development and demo purposes
 */

import { RegisteredModel, ModelDetails, ModelVersion } from './modelRegistryService';

export const mockModels: RegisteredModel[] = [
  {
    id: 'model_001',
    name: 'Loan Approval Classifier',
    description: 'Advanced classification model for predicting loan approval decisions with 85% accuracy',
    problem_type: 'classification',
    current_version: 'v1.2',
    latest_version: 'v1.2',
    total_versions: 3,
    status: 'production',
    best_accuracy: 0.85,
    best_algorithm: 'AdaBoostClassifier',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-06T17:30:00Z',
    created_by: 'john.doe@company.com',
    is_deployed: true,
    deployment_url: 'https://api.company.com/models/loan-approval/predict',
    deployed_version: 'v1.2',
    deployed_at: '2026-02-06T17:35:00Z',
    source_dataset_id: 'dataset_123',
    source_dataset_name: 'Loan Applications Dataset',
    training_job_id: 'bf5df478-6cf8-4dea-914a-3d110ba5ffb2',
    tags: ['production', 'finance', 'high-priority'],
    labels: {
      department: 'Risk Management',
      compliance: 'approved',
      priority: 'high'
    },
    versions: [
      {
        version: 'v1.2',
        version_number: 3,
        status: 'production',
        algorithm: 'AdaBoostClassifier',
        accuracy: 0.85,
        precision: 0.83,
        recall: 0.85,
        f1_score: 0.84,
        created_at: '2026-02-06T17:30:00Z',
        created_by: 'john.doe@company.com',
        job_id: 'bf5df478-6cf8-4dea-914a-3d110ba5ffb2',
        is_current: true,
        tags: ['production', 'stable'],
        model_size_mb: 2.4,
        training_time_seconds: 55.18,
      },
      {
        version: 'v1.1',
        version_number: 2,
        status: 'archived',
        algorithm: 'RandomForestClassifier',
        accuracy: 0.83,
        precision: 0.82,
        recall: 0.83,
        f1_score: 0.825,
        created_at: '2026-02-05T14:20:00Z',
        created_by: 'john.doe@company.com',
        job_id: 'abc123-prev-job',
        is_current: false,
        tags: ['archived'],
        model_size_mb: 5.1,
        training_time_seconds: 120.5,
      },
      {
        version: 'v1.0',
        version_number: 1,
        status: 'archived',
        algorithm: 'LogisticRegression',
        accuracy: 0.79,
        precision: 0.78,
        recall: 0.79,
        f1_score: 0.785,
        created_at: '2026-02-01T10:00:00Z',
        created_by: 'john.doe@company.com',
        job_id: 'xyz789-first-job',
        is_current: false,
        tags: ['archived', 'baseline'],
        model_size_mb: 0.8,
        training_time_seconds: 45.2,
      },
    ],
  },
  {
    id: 'model_002',
    name: 'Customer Churn Predictor',
    description: 'Predicts customer churn probability with high accuracy for subscription services',
    problem_type: 'classification',
    current_version: 'v2.0',
    latest_version: 'v2.0',
    total_versions: 2,
    status: 'staging',
    best_accuracy: 0.892,
    best_algorithm: 'XGBoostClassifier',
    created_at: '2026-01-28T09:00:00Z',
    updated_at: '2026-02-05T16:00:00Z',
    created_by: 'sarah.smith@company.com',
    is_deployed: false,
    source_dataset_id: 'dataset_456',
    source_dataset_name: 'Customer Behavior Dataset',
    training_job_id: 'churn-job-456',
    tags: ['staging', 'customer-success', 'testing'],
    labels: {
      department: 'Customer Success',
      priority: 'medium'
    },
    versions: [
      {
        version: 'v2.0',
        version_number: 2,
        status: 'staging',
        algorithm: 'XGBoostClassifier',
        accuracy: 0.892,
        precision: 0.88,
        recall: 0.89,
        f1_score: 0.885,
        created_at: '2026-02-05T16:00:00Z',
        created_by: 'sarah.smith@company.com',
        job_id: 'churn-job-456',
        is_current: true,
        tags: ['staging', 'testing'],
        model_size_mb: 8.2,
        training_time_seconds: 180.3,
      },
      {
        version: 'v1.0',
        version_number: 1,
        status: 'archived',
        algorithm: 'GradientBoostingClassifier',
        accuracy: 0.856,
        precision: 0.84,
        recall: 0.85,
        f1_score: 0.845,
        created_at: '2026-01-28T09:00:00Z',
        created_by: 'sarah.smith@company.com',
        job_id: 'churn-job-123',
        is_current: false,
        tags: ['archived'],
        model_size_mb: 6.5,
        training_time_seconds: 156.7,
      },
    ],
  },
  {
    id: 'model_003',
    name: 'House Price Estimator',
    description: 'Regression model for predicting house prices based on location and features',
    problem_type: 'regression',
    current_version: 'v1.0',
    latest_version: 'v1.0',
    total_versions: 1,
    status: 'draft',
    best_accuracy: 0.912,
    best_algorithm: 'RandomForestRegressor',
    created_at: '2026-02-06T08:00:00Z',
    updated_at: '2026-02-06T08:00:00Z',
    created_by: 'mike.johnson@company.com',
    is_deployed: false,
    source_dataset_id: 'dataset_789',
    source_dataset_name: 'Housing Market Data',
    training_job_id: 'housing-job-789',
    tags: ['draft', 'real-estate'],
    labels: {
      department: 'Real Estate Analytics',
      priority: 'low'
    },
    versions: [
      {
        version: 'v1.0',
        version_number: 1,
        status: 'draft',
        algorithm: 'RandomForestRegressor',
        accuracy: 0.912,
        created_at: '2026-02-06T08:00:00Z',
        created_by: 'mike.johnson@company.com',
        job_id: 'housing-job-789',
        is_current: true,
        tags: ['draft'],
        model_size_mb: 12.3,
        training_time_seconds: 210.5,
      },
    ],
  },
];

export const mockModelDetails: ModelDetails = {
  ...mockModels[0],
  
  features: [
    'credit_score',
    'annual_income',
    'loan_amount',
    'employment_length',
    'debt_to_income_ratio',
    'number_of_accounts',
    'delinquencies_last_2yrs',
  ],
  
  feature_importance: {
    credit_score: 0.28,
    annual_income: 0.22,
    debt_to_income_ratio: 0.18,
    loan_amount: 0.14,
    employment_length: 0.09,
    number_of_accounts: 0.06,
    delinquencies_last_2yrs: 0.03,
  },
  
  hyperparameters: {
    n_estimators: 50,
    learning_rate: 1.0,
    algorithm: 'SAMME.R',
    random_state: 42,
    base_estimator: 'DecisionTreeClassifier',
    max_depth: 1,
  },
  
  training_config: {
    dataset_id: 'dataset_123',
    dataset_name: 'Loan Applications Dataset',
    target_column: 'loan_approved',
    train_test_split: 0.8,
    cross_validation_folds: 5,
    random_seed: 42,
  },
  
  metrics: {
    train_score: 0.8525,
    test_score: 0.85,
    validation_score: 0.8387,
    confusion_matrix: [
      [85, 15],
      [15, 85],
    ],
    roc_auc: 0.8365,
    feature_count: 7,
    sample_count: 1000,
  },
  
  artifacts: {
    model_file: '/models/loan_approval_v1.2.pkl',
    scaler_file: '/models/loan_approval_scaler_v1.2.pkl',
    feature_selector_file: '/models/loan_approval_features_v1.2.pkl',
    training_report: '/reports/loan_approval_training_v1.2.pdf',
    confusion_matrix_plot: '/plots/loan_approval_cm_v1.2.png',
    roc_curve_plot: '/plots/loan_approval_roc_v1.2.png',
    feature_importance_plot: '/plots/loan_approval_fi_v1.2.png',
  },
  
  deployment_history: [
    {
      version: 'v1.2',
      action: 'deployed',
      environment: 'production',
      timestamp: '2026-02-06T17:35:00Z',
      deployed_by: 'john.doe@company.com',
      notes: 'Deployed new version with improved accuracy',
    },
    {
      version: 'v1.1',
      action: 'rolled_back',
      environment: 'production',
      timestamp: '2026-02-05T18:00:00Z',
      deployed_by: 'john.doe@company.com',
      notes: 'Performance issues detected, rolling back',
    },
    {
      version: 'v1.1',
      action: 'deployed',
      environment: 'production',
      timestamp: '2026-02-05T14:30:00Z',
      deployed_by: 'john.doe@company.com',
    },
    {
      version: 'v1.0',
      action: 'deployed',
      environment: 'production',
      timestamp: '2026-02-01T10:30:00Z',
      deployed_by: 'john.doe@company.com',
      notes: 'Initial production deployment',
    },
  ],
  
  lineage: {
    source_data: 'Loan Applications Dataset (10,000 records)',
    preprocessing_pipeline: 'Phase 1-2: Data Cleaning + Feature Engineering',
    training_job: 'ML Flow - Phase 3-4 Pipeline',
    parent_model_id: undefined,
  },
};
